const NcertSubjects = [
  {
    class: "CLASS-1",
    subjects: ["ENGLISH", "MATHEMATICS", "HINDI", "Urdu"],
  },
  {
    class: "CLASS-2",
    subjects: ["MATHEMATICS", "HINDI", "ENGLISH", "URDU"],
  },
  {
    class: "CLASS-3",
    subjects: [
      "MATHEMATICS",
      "ENGLISH",
      "HINDI",
      "THE WORLD AROUND US",
      "ARTS",
      "PHYSICAL EDUCATION AND WELL BEING",
      "URDU",
    ],
  },
  {
    class: "CLASS-4",
    subjects: [
      "MATHEMATICS",
      "HINDI",
      "ENGLISH",
      "THE WORLD AROUND US",
      "ARTS",
      "PHYSICAL EDUCATION AND WELL BEING",
      "URDU",
    ],
  },
  {
    class: "CLASS-5",
    subjects: [
      "MATHEMATICS",
      "HINDI",
      "ENGLISH",
      "THE WORLD AROUND US",
      "ARTS",
      "PHYSICAL EDUCATION AND WELL BEING",
      "URDU",
    ],
  },
  {
    class: "CLASS-6",
    subjects: [
      "HINDI",
      "ENGLISH",
      "MATHEMATICS",
      "SOCIAL SCIENCE",
      "SANSKRIT",
      "SCIENCE",
      "ARTS",
      "PHYSICAL EDUCATION AND WELL BEING",
      "VOCATIONAL EDUCATION",
      "URDU",
    ],
  },
  {
    class: "CLASS-7",
    subjects: [
      "HINDI",
      "ENGLISH",
      "MATHEMATICS",
      "SOCIAL SCIENCE",
      "SANSKRIT",
      "SCIENCE",
      "ARTS",
      "PHYSICAL EDUCATION AND WELL BEING",
      "VOCATIONAL EDUCATION",
      "URDU",
    ],
  },
  {
    class: "CLASS-8",
    subjects: [
      "HINDI",
      "ENGLISH",
      "MATHEMATICS",
      "SOCIAL SCIENCE",
      "SANSKRIT",
      "SCIENCE",
      "ARTS",
      "PHYSICAL EDUCATION AND WELL BEING",
      "VOCATIONAL EDUCATION",
      "URDU",
    ],
  },
  {
    class: "CLASS-9",
    subjects: [
      "ENGLISH",
      "HINDI",
      "SANSKRIT",
      "MATHEMATICS",
      "SCIENCE",
      "SOCIAL SCIENCE",
      "URDU",
      "HEALTH AND PHYSICAL EDUCATION",
      "ICT",
    ],
  },
  {
    class: "CLASS-10",
    subjects: [
      "MATHEMATICS",
      "SCIENCE",
      "HINDI",
      "SOCIAL SCIENCE",
      "ENGLISH",
      "SANSKRIT",
      "URDU",
      "HEALTH AND PHYSICAL EDUCATION",
    ],
  },
  {
    class: "CLASS-11",
    subjects: [
      "SANSKRIT",
      "ACCOUNTANCY",
      "CHEMISTRY",
      "MATHEMATICS",
      "BIOLOGY",
      "PSYCHOLOGY",
      "GEOGRAPHY",
      "PHYSICS",
      "HINDI",
      "SOCIOLOGY",
      "ENGLISH",
      "POLITICAL SCIENCE",
      "HISTORY",
      "ECONOMICS",
      "BUISNESS STUDIES",
      "URDU",
      "HOME SCIENCE",
      "CREATIVE WRITING AND TRANSLATION",
      "FINE ARTS",
      "IMFORMATION PRACTICE",
      "COMPUTER SCIENCE",
      "HEALTH AND PHYSICAL EDUCATION",
      "BIOTECHNOLOGY",
      "SANGEET",
      "KNOWLEDGE TRADITIONS PRACTICES OF INDIA",
    ],
  },
  {
    class: "CLASS-12",
    subjects: [
      "MATHEMATICS",
      "PHYSICS",
      "ACCOUNTANCY",
      "SANSKRIT",
      "HINDI",
      "ENGLISH",
      "BIOLOGY",
      "HISTORY",
      "GEOGRAPHY",
      "PSYCHOLOGY",
      "SOCIOLOGY",
      "CHEMISTRY",
      "POLITICAL SCIENCE",
      "ECONOMICS",
      "BUISNESS STUDIES",
      "HOME SCIENCE",
      "URDU",
      "CREATIVE WRITING AND TRANSLATION",
      "FINE ARTS",
      "COMPUTER SCIENCE",
      "IMFORMATION PRACTICE",
      "BIOTECHNOLOGY",
      "SANGEET",
    ],
  },
  {
    class: "Class XI & XII Combined",
    subjects: ["HINDI", "SANSKRIT", "URDU"],
  },
];

export default NcertSubjects;
