const NcertSubjects = [
  {
    class: "CLASS-1",
    subjects: ["ENGLISH", "MATHEMATICS", "HINDI", "URDU"],
    subjectsEndPageNo: {
      ENGLISH: 135,
      MATHEMATICS: 143,
      HINDI: 135,
      URDU: 119,
    },
  },
  {
    class: "CLASS-2",
    subjects: ["MATHEMATICS", "HINDI", "ENGLISH", "URDU"],
    subjectsEndPageNo: {
      MATHEMATICS: 145,
      HINDI: 140,
      ENGLISH: 138,
      URDU: 125,
    },
  },
  {
    class: "CLASS-3",
    subjects: [
      "MATHEMATICS",
      "ENGLISH",
      "HINDI",
      "THE WORLD AROUND US",
      "ARTS",
      "PHYSICAL EDUCATION AND WELL BEING",
      "URDU",
    ],
    subjectsEndPageNo: {
      MATHEMATICS: 150,
      ENGLISH: 145,
      HINDI: 142,
      "THE WORLD AROUND US": 130,
      ARTS: 70,
      "PHYSICAL EDUCATION AND WELL BEING": 60,
      URDU: 128,
    },
  },
  {
    class: "CLASS-4",
    subjects: [
      "MATHEMATICS",
      "HINDI",
      "ENGLISH",
      "THE WORLD AROUND US",
      "ARTS",
      "PHYSICAL EDUCATION AND WELL BEING",
      "URDU",
    ],
    subjectsEndPageNo: {
      MATHEMATICS: 158,
      HINDI: 150,
      ENGLISH: 147,
      "THE WORLD AROUND US": 135,
      ARTS: 72,
      "PHYSICAL EDUCATION AND WELL BEING": 65,
      URDU: 130,
    },
  },
  {
    class: "CLASS-5",
    subjects: [
      "MATHEMATICS",
      "HINDI",
      "ENGLISH",
      "THE WORLD AROUND US",
      "ARTS",
      "PHYSICAL EDUCATION AND WELL BEING",
      "URDU",
    ],
    subjectsEndPageNo: {
      MATHEMATICS: 165,
      HINDI: 155,
      ENGLISH: 152,
      "THE WORLD AROUND US": 140,
      ARTS: 75,
      "PHYSICAL EDUCATION AND WELL BEING": 68,
      URDU: 132,
    },
  },
  {
    class: "CLASS-6",
    subjects: [
      "HINDI",
      "ENGLISH",
      "MATHEMATICS",
      "SOCIAL SCIENCE",
      "SANSKRIT",
      "SCIENCE",
      "ARTS",
      "PHYSICAL EDUCATION AND WELL BEING",
      "VOCATIONAL EDUCATION",
      "URDU",
    ],
    subjectsEndPageNo: {
      HINDI: 180,
      ENGLISH: 170,
      MATHEMATICS: 190,
      "SOCIAL SCIENCE": 160,
      SANSKRIT: 120,
      SCIENCE: 175,
      ARTS: 85,
      "PHYSICAL EDUCATION AND WELL BEING": 80,
      "VOCATIONAL EDUCATION": 70,
      URDU: 135,
    },
  },
  {
    class: "CLASS-7",
    subjects: [
      "HINDI",
      "ENGLISH",
      "MATHEMATICS",
      "SOCIAL SCIENCE",
      "SANSKRIT",
      "SCIENCE",
      "ARTS",
      "PHYSICAL EDUCATION AND WELL BEING",
      "VOCATIONAL EDUCATION",
      "URDU",
    ],
    subjectsEndPageNo: {
      HINDI: 185,
      ENGLISH: 175,
      MATHEMATICS: 195,
      "SOCIAL SCIENCE": 165,
      SANSKRIT: 125,
      SCIENCE: 180,
      ARTS: 88,
      "PHYSICAL EDUCATION AND WELL BEING": 82,
      "VOCATIONAL EDUCATION": 72,
      URDU: 138,
    },
  },
  {
    class: "CLASS-8",
    subjects: [
      "HINDI",
      "ENGLISH",
      "MATHEMATICS",
      "SOCIAL SCIENCE",
      "SANSKRIT",
      "SCIENCE",
      "ARTS",
      "PHYSICAL EDUCATION AND WELL BEING",
      "VOCATIONAL EDUCATION",
      "URDU",
    ],
    subjectsEndPageNo: {
      HINDI: 190,
      ENGLISH: 180,
      MATHEMATICS: 200,
      "SOCIAL SCIENCE": 170,
      SANSKRIT: 130,
      SCIENCE: 185,
      ARTS: 90,
      "PHYSICAL EDUCATION AND WELL BEING": 85,
      "VOCATIONAL EDUCATION": 75,
      URDU: 140,
    },
  },
  {
    class: "CLASS-9",
    subjects: [
      "ENGLISH",
      "HINDI",
      "SANSKRIT",
      "MATHEMATICS",
      "SCIENCE",
      "SOCIAL SCIENCE",
      "URDU",
      "HEALTH AND PHYSICAL EDUCATION",
      "ICT",
    ],
    subjectsEndPageNo: {
      ENGLISH: 200,
      HINDI: 195,
      SANSKRIT: 140,
      MATHEMATICS: 210,
      SCIENCE: 210,
      "SOCIAL SCIENCE": 190,
      URDU: 150,
      "HEALTH AND PHYSICAL EDUCATION": 90,
      ICT: 100,
    },
  },
  {
    class: "CLASS-10",
    subjects: [
      "MATHEMATICS",
      "SCIENCE",
      "HINDI",
      "SOCIAL SCIENCE",
      "ENGLISH",
      "SANSKRIT",
      "URDU",
      "HEALTH AND PHYSICAL EDUCATION",
    ],
    subjectsEndPageNo: {
      MATHEMATICS: 220,
      SCIENCE: 215,
      HINDI: 200,
      "SOCIAL SCIENCE": 195,
      ENGLISH: 205,
      SANSKRIT: 145,
      URDU: 155,
      "HEALTH AND PHYSICAL EDUCATION": 92,
    },
  },
  {
    class: "CLASS-11",
    subjects: [
      "SANSKRIT",
      "ACCOUNTANCY",
      "CHEMISTRY",
      "MATHEMATICS",
      "BIOLOGY",
      "PSYCHOLOGY",
      "GEOGRAPHY",
      "PHYSICS",
      "HINDI",
      "SOCIOLOGY",
      "ENGLISH",
      "POLITICAL SCIENCE",
      "HISTORY",
      "ECONOMICS",
      "BUISNESS STUDIES",
      "URDU",
      "HOME SCIENCE",
      "CREATIVE WRITING AND TRANSLATION",
      "FINE ARTS",
      "IMFORMATION PRACTICE",
      "COMPUTER SCIENCE",
      "HEALTH AND PHYSICAL EDUCATION",
      "BIOTECHNOLOGY",
      "SANGEET",
      "KNOWLEDGE TRADITIONS PRACTICES OF INDIA",
    ],
    subjectsEndPageNo: {
      SANSKRIT: 160,
      ACCOUNTANCY: 240,
      CHEMISTRY: 230,
      MATHEMATICS: 250,
      BIOLOGY: 260,
      PSYCHOLOGY: 190,
      GEOGRAPHY: 220,
      PHYSICS: 240,
      HINDI: 210,
      SOCIOLOGY: 200,
      ENGLISH: 215,
      "POLITICAL SCIENCE": 210,
      HISTORY: 230,
      ECONOMICS: 225,
      "BUISNESS STUDIES": 235,
      URDU: 180,
      "HOME SCIENCE": 185,
      "CREATIVE WRITING AND TRANSLATION": 160,
      "FINE ARTS": 170,
      "IMFORMATION PRACTICE": 190,
      "COMPUTER SCIENCE": 200,
      "HEALTH AND PHYSICAL EDUCATION": 100,
      BIOTECHNOLOGY: 210,
      SANGEET: 150,
      "KNOWLEDGE TRADITIONS PRACTICES OF INDIA": 165,
    },
  },
  {
    class: "CLASS-12",
    subjects: [
      "MATHEMATICS",
      "PHYSICS",
      "ACCOUNTANCY",
      "SANSKRIT",
      "HINDI",
      "ENGLISH",
      "BIOLOGY",
      "HISTORY",
      "GEOGRAPHY",
      "PSYCHOLOGY",
      "SOCIOLOGY",
      "CHEMISTRY",
      "POLITICAL SCIENCE",
      "ECONOMICS",
      "BUISNESS STUDIES",
      "HOME SCIENCE",
      "URDU",
      "CREATIVE WRITING AND TRANSLATION",
      "FINE ARTS",
      "COMPUTER SCIENCE",
      "IMFORMATION PRACTICE",
      "BIOTECHNOLOGY",
      "SANGEET",
    ],
    subjectsEndPageNo: {
      MATHEMATICS: 260,
      PHYSICS: 255,
      ACCOUNTANCY: 245,
      SANSKRIT: 165,
      HINDI: 215,
      ENGLISH: 225,
      BIOLOGY: 270,
      HISTORY: 240,
      GEOGRAPHY: 230,
      PSYCHOLOGY: 200,
      SOCIOLOGY: 210,
      CHEMISTRY: 250,
      "POLITICAL SCIENCE": 220,
      ECONOMICS: 235,
      "BUISNESS STUDIES": 240,
      "HOME SCIENCE": 190,
      URDU: 185,
      "CREATIVE WRITING AND TRANSLATION": 170,
      "FINE ARTS": 175,
      "COMPUTER SCIENCE": 210,
      "IMFORMATION PRACTICE": 195,
      BIOTECHNOLOGY: 215,
      SANGEET: 155,
    },
  },
  {
    class: "Class XI & XII Combined",
    subjects: ["HINDI", "SANSKRIT", "URDU"],
    subjectsEndPageNo: {
      HINDI: 215,
      SANSKRIT: 165,
      URDU: 185,
    },
  },
];

export default NcertSubjects;
